// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/seizadi/atlas-cli-test/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	_ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Account struct {
	// The Account identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Account
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the Account
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateAccountRequest struct {
	Payload              *Account `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetPayload() *Account {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateAccountResponse struct {
	Result               *Account `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetResult() *Account {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadAccountRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadAccountRequest) Reset()         { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()    {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{4}
}

func (m *ReadAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRequest.Unmarshal(m, b)
}
func (m *ReadAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRequest.Marshal(b, m, deterministic)
}
func (m *ReadAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRequest.Merge(m, src)
}
func (m *ReadAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRequest.Size(m)
}
func (m *ReadAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRequest proto.InternalMessageInfo

func (m *ReadAccountRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadAccountRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadAccountResponse struct {
	Result               *Account `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountResponse) Reset()         { *m = ReadAccountResponse{} }
func (m *ReadAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAccountResponse) ProtoMessage()    {}
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{5}
}

func (m *ReadAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountResponse.Unmarshal(m, b)
}
func (m *ReadAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountResponse.Marshal(b, m, deterministic)
}
func (m *ReadAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountResponse.Merge(m, src)
}
func (m *ReadAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAccountResponse.Size(m)
}
func (m *ReadAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountResponse proto.InternalMessageInfo

func (m *ReadAccountResponse) GetResult() *Account {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateAccountRequest struct {
	Payload              *Account              `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{6}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetPayload() *Account {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateAccountRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateAccountResponse struct {
	Result               *Account `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{7}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetResult() *Account {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteAccountRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{8}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{9}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

type ListAccountRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListAccountRequest) Reset()         { *m = ListAccountRequest{} }
func (m *ListAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountRequest) ProtoMessage()    {}
func (*ListAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{10}
}

func (m *ListAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountRequest.Unmarshal(m, b)
}
func (m *ListAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountRequest.Merge(m, src)
}
func (m *ListAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountRequest.Size(m)
}
func (m *ListAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountRequest proto.InternalMessageInfo

func (m *ListAccountRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListAccountRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListAccountRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListAccountRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListAccountsResponse struct {
	Results              []*Account      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{11}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetResults() []*Account {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListAccountsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type User struct {
	// The User identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the User
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the User
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserRequest struct {
	Payload              *User    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{13}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{14}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadUserRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{15}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadUserRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{16}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateUserRequest struct {
	Payload              *User                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{17}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateUserRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{18}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{19}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{20}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type ListUserRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{21}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListUserRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListUserRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListUserRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListUsersResponse struct {
	Results              []*User         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{22}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetResults() []*User {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListUsersResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type Group struct {
	// The Group identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Group
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the Group
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{23}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateGroupRequest struct {
	Payload              *Group   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{24}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{25}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadGroupRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadGroupRequest) Reset()         { *m = ReadGroupRequest{} }
func (m *ReadGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ReadGroupRequest) ProtoMessage()    {}
func (*ReadGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{26}
}

func (m *ReadGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGroupRequest.Unmarshal(m, b)
}
func (m *ReadGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGroupRequest.Marshal(b, m, deterministic)
}
func (m *ReadGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGroupRequest.Merge(m, src)
}
func (m *ReadGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ReadGroupRequest.Size(m)
}
func (m *ReadGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGroupRequest proto.InternalMessageInfo

func (m *ReadGroupRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadGroupRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadGroupResponse) Reset()         { *m = ReadGroupResponse{} }
func (m *ReadGroupResponse) String() string { return proto.CompactTextString(m) }
func (*ReadGroupResponse) ProtoMessage()    {}
func (*ReadGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{27}
}

func (m *ReadGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadGroupResponse.Unmarshal(m, b)
}
func (m *ReadGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadGroupResponse.Marshal(b, m, deterministic)
}
func (m *ReadGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadGroupResponse.Merge(m, src)
}
func (m *ReadGroupResponse) XXX_Size() int {
	return xxx_messageInfo_ReadGroupResponse.Size(m)
}
func (m *ReadGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadGroupResponse proto.InternalMessageInfo

func (m *ReadGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateGroupRequest struct {
	Payload              *Group                `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{28}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetPayload() *Group {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateGroupRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateGroupResponse struct {
	Result               *Group   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupResponse) Reset()         { *m = UpdateGroupResponse{} }
func (m *UpdateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupResponse) ProtoMessage()    {}
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{29}
}

func (m *UpdateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupResponse.Unmarshal(m, b)
}
func (m *UpdateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupResponse.Marshal(b, m, deterministic)
}
func (m *UpdateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupResponse.Merge(m, src)
}
func (m *UpdateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupResponse.Size(m)
}
func (m *UpdateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupResponse proto.InternalMessageInfo

func (m *UpdateGroupResponse) GetResult() *Group {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{30}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupResponse) Reset()         { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupResponse) ProtoMessage()    {}
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{31}
}

func (m *DeleteGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupResponse.Unmarshal(m, b)
}
func (m *DeleteGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupResponse.Merge(m, src)
}
func (m *DeleteGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupResponse.Size(m)
}
func (m *DeleteGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupResponse proto.InternalMessageInfo

type ListGroupRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListGroupRequest) Reset()         { *m = ListGroupRequest{} }
func (m *ListGroupRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupRequest) ProtoMessage()    {}
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{32}
}

func (m *ListGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupRequest.Unmarshal(m, b)
}
func (m *ListGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupRequest.Merge(m, src)
}
func (m *ListGroupRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupRequest.Size(m)
}
func (m *ListGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupRequest proto.InternalMessageInfo

func (m *ListGroupRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListGroupRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListGroupRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListGroupRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListGroupsResponse struct {
	Results              []*Group        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7525abf22c2fb858, []int{33}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetResults() []*Group {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListGroupsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*Account)(nil), "service.Account")
	proto.RegisterType((*CreateAccountRequest)(nil), "service.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "service.CreateAccountResponse")
	proto.RegisterType((*ReadAccountRequest)(nil), "service.ReadAccountRequest")
	proto.RegisterType((*ReadAccountResponse)(nil), "service.ReadAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "service.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "service.UpdateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "service.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "service.DeleteAccountResponse")
	proto.RegisterType((*ListAccountRequest)(nil), "service.ListAccountRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "service.ListAccountsResponse")
	proto.RegisterType((*User)(nil), "service.User")
	proto.RegisterType((*CreateUserRequest)(nil), "service.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "service.CreateUserResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "service.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "service.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "service.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "service.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "service.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "service.DeleteUserResponse")
	proto.RegisterType((*ListUserRequest)(nil), "service.ListUserRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "service.ListUsersResponse")
	proto.RegisterType((*Group)(nil), "service.Group")
	proto.RegisterType((*CreateGroupRequest)(nil), "service.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "service.CreateGroupResponse")
	proto.RegisterType((*ReadGroupRequest)(nil), "service.ReadGroupRequest")
	proto.RegisterType((*ReadGroupResponse)(nil), "service.ReadGroupResponse")
	proto.RegisterType((*UpdateGroupRequest)(nil), "service.UpdateGroupRequest")
	proto.RegisterType((*UpdateGroupResponse)(nil), "service.UpdateGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "service.DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupResponse)(nil), "service.DeleteGroupResponse")
	proto.RegisterType((*ListGroupRequest)(nil), "service.ListGroupRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "service.ListGroupsResponse")
}

func init() {
	proto.RegisterFile("github.com/seizadi/atlas-cli-test/pkg/pb/service.proto", fileDescriptor_7525abf22c2fb858)
}

var fileDescriptor_7525abf22c2fb858 = []byte{
	// 1433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xdf, 0x6e, 0xdc, 0x44,
	0x17, 0xef, 0xa6, 0xdb, 0xdd, 0xcd, 0x49, 0xbf, 0x26, 0x3b, 0x49, 0x9a, 0x5d, 0x27, 0xfd, 0xba,
	0xb2, 0xd4, 0xaf, 0xf9, 0x36, 0xac, 0x5d, 0x2d, 0x08, 0x44, 0x42, 0x41, 0x49, 0x29, 0x55, 0x51,
	0x81, 0x6a, 0xfb, 0x47, 0xa8, 0x2a, 0x0a, 0x5e, 0x7b, 0xe2, 0x9a, 0x38, 0x1e, 0xd7, 0xf6, 0x86,
	0x06, 0x84, 0x40, 0x7d, 0x05, 0x9e, 0x81, 0x0b, 0xae, 0x10, 0x97, 0xc9, 0x0d, 0xe2, 0x19, 0xb8,
	0x43, 0x20, 0x6e, 0xe0, 0x3d, 0x90, 0x67, 0xc6, 0xde, 0xf1, 0xd8, 0x4b, 0x77, 0x17, 0x55, 0x95,
	0x7a, 0xb7, 0xf6, 0x39, 0xf3, 0x3b, 0xe7, 0xfc, 0xe6, 0x77, 0xc6, 0x67, 0x16, 0x5e, 0xb7, 0x9d,
	0xe8, 0xd1, 0xa0, 0xaf, 0x99, 0xe4, 0x40, 0x0f, 0xb1, 0xf3, 0x85, 0x61, 0x39, 0xba, 0x11, 0xb9,
	0x46, 0xd8, 0x31, 0x5d, 0xa7, 0x13, 0xe1, 0x30, 0xd2, 0xfd, 0x7d, 0x5b, 0xf7, 0xfb, 0x7a, 0x88,
	0x83, 0x43, 0xc7, 0xc4, 0x9a, 0x1f, 0x90, 0x88, 0xa0, 0x2a, 0x7f, 0x54, 0x56, 0x6d, 0x42, 0x6c,
	0x17, 0xeb, 0xf4, 0x75, 0x7f, 0xb0, 0xa7, 0xe3, 0x03, 0x3f, 0x3a, 0x62, 0x5e, 0xca, 0x1a, 0x37,
	0x1a, 0xbe, 0xa3, 0x1b, 0x9e, 0x47, 0x22, 0x23, 0x72, 0x88, 0x17, 0x72, 0xeb, 0x96, 0x10, 0xdb,
	0x3d, 0xda, 0x8b, 0x18, 0x86, 0xd9, 0xb1, 0xb1, 0xd7, 0x39, 0x34, 0x5c, 0xc7, 0x32, 0x22, 0xac,
	0xe7, 0x7e, 0xf0, 0xc5, 0xaf, 0x08, 0xce, 0xe1, 0xe7, 0x86, 0x6d, 0xe3, 0x40, 0x27, 0x3e, 0x85,
	0x2f, 0x08, 0xb5, 0x29, 0x84, 0x72, 0xbc, 0x3d, 0xd2, 0x77, 0xc9, 0x13, 0xe2, 0x63, 0x4f, 0x0c,
	0x69, 0x93, 0xe0, 0x20, 0x85, 0x88, 0x1f, 0xf8, 0xda, 0x96, 0x5c, 0xe1, 0x9e, 0x83, 0x5d, 0x6b,
	0xf7, 0xc0, 0x08, 0xf7, 0xb9, 0xc7, 0xfb, 0xa3, 0xd0, 0x19, 0x93, 0x86, 0xef, 0x77, 0x22, 0x42,
	0xdc, 0x7d, 0x27, 0xd2, 0x1f, 0x0f, 0x70, 0x70, 0xa4, 0x9b, 0xc4, 0x75, 0xb1, 0x19, 0x47, 0xda,
	0x25, 0x3e, 0x0e, 0x8c, 0x88, 0x04, 0x49, 0xa6, 0xd7, 0xc7, 0xc7, 0x0a, 0x7c, 0x53, 0x0f, 0x70,
	0x48, 0x06, 0x81, 0x89, 0xd3, 0x1f, 0x1c, 0xe6, 0xee, 0x18, 0x05, 0x33, 0x44, 0x9a, 0xd1, 0x90,
	0xef, 0x84, 0x00, 0xfa, 0x7a, 0x57, 0x22, 0xfd, 0xc3, 0xb1, 0x51, 0x73, 0x78, 0xf4, 0xb5, 0x84,
	0xa7, 0x6e, 0xc0, 0xfc, 0x7d, 0x1c, 0x84, 0x0e, 0xf1, 0x7a, 0x38, 0xf4, 0x89, 0x17, 0x62, 0xd4,
	0x80, 0xea, 0x21, 0x7b, 0xd5, 0x28, 0xb5, 0x4a, 0xeb, 0xb3, 0xbd, 0xe4, 0x51, 0x7d, 0x5a, 0x82,
	0xea, 0xb6, 0x69, 0x92, 0x81, 0x17, 0xa1, 0x37, 0x60, 0xc6, 0xb1, 0xa8, 0xc3, 0x5c, 0x77, 0x59,
	0xa3, 0xd8, 0x5a, 0xe0, 0x9b, 0xda, 0x4d, 0x0b, 0x7b, 0x91, 0xb3, 0xe7, 0xe0, 0x60, 0x67, 0xe1,
	0xe4, 0xb8, 0x79, 0x16, 0x00, 0x55, 0x42, 0x1c, 0x38, 0x86, 0xbb, 0x5e, 0xea, 0xcd, 0x38, 0x16,
	0x42, 0x50, 0xf6, 0x8c, 0x03, 0xdc, 0x98, 0xa1, 0xd8, 0xf4, 0x37, 0x6a, 0xc1, 0x9c, 0x85, 0x43,
	0x33, 0x70, 0x68, 0xaa, 0x8d, 0xd3, 0xd4, 0x24, 0xbe, 0xda, 0xac, 0x9d, 0x1c, 0x37, 0xcb, 0xb5,
	0x52, 0xeb, 0x94, 0xba, 0x03, 0x4b, 0xd7, 0x02, 0x6c, 0x44, 0x98, 0x67, 0xd2, 0xc3, 0x8f, 0x07,
	0x38, 0x8c, 0x50, 0x1b, 0xaa, 0xbe, 0x71, 0xe4, 0x12, 0x23, 0xc9, 0x6a, 0x41, 0x4b, 0x1a, 0x26,
	0xf1, 0x4c, 0x1c, 0xd4, 0x6d, 0x58, 0x96, 0x30, 0x78, 0xed, 0xeb, 0x50, 0x09, 0x70, 0x38, 0x70,
	0xa3, 0x91, 0x18, 0xdc, 0xae, 0x3e, 0x06, 0xd4, 0xc3, 0x86, 0x25, 0x25, 0x71, 0xe9, 0x99, 0xac,
	0x50, 0x0e, 0x5e, 0x83, 0x0a, 0x95, 0x70, 0x48, 0x59, 0x98, 0xeb, 0xae, 0x69, 0xc9, 0x5e, 0x6a,
	0x86, 0xef, 0x68, 0xef, 0xc5, 0xb6, 0x3b, 0x98, 0x0b, 0xb4, 0xc7, 0x7d, 0xd5, 0x77, 0x60, 0x31,
	0x13, 0x72, 0xe2, 0x9c, 0x0f, 0x61, 0xe9, 0x9e, 0x6f, 0xfd, 0x2b, 0xea, 0x50, 0x57, 0x4a, 0x5d,
	0xd1, 0x58, 0x73, 0x6a, 0x49, 0x73, 0xb2, 0xec, 0x3f, 0x30, 0xc2, 0xfd, 0x34, 0xf1, 0x6d, 0x58,
	0x96, 0xe2, 0x4e, 0x9c, 0xfa, 0x55, 0x58, 0x7a, 0x17, 0xbb, 0x38, 0x97, 0xfa, 0x78, 0x84, 0xab,
	0x2b, 0xb0, 0x2c, 0x2d, 0x67, 0x19, 0xa8, 0x7f, 0x94, 0x00, 0xdd, 0x72, 0xc2, 0x48, 0x82, 0xd5,
	0xe3, 0x2a, 0xdd, 0x08, 0x07, 0x1c, 0x7a, 0x45, 0xde, 0xa0, 0xd8, 0xe6, 0x78, 0x76, 0x8f, 0xbb,
	0xa1, 0x2b, 0x50, 0x23, 0x81, 0x85, 0x83, 0xdd, 0xfe, 0x11, 0x27, 0x66, 0x39, 0xbb, 0xe4, 0x0e,
	0x09, 0xa2, 0x78, 0x41, 0x95, 0xba, 0xed, 0x1c, 0x09, 0x1a, 0x38, 0x3d, 0xbe, 0x06, 0xd0, 0x15,
	0xa8, 0xf8, 0x86, 0xed, 0x78, 0x76, 0xa3, 0x4c, 0x57, 0x35, 0xb2, 0xab, 0x6e, 0xc7, 0x36, 0x83,
	0xad, 0x60, 0x7e, 0xaa, 0x07, 0x4b, 0x42, 0x81, 0x61, 0xca, 0x7d, 0x1b, 0xaa, 0x8c, 0xdb, 0xb0,
	0x51, 0x6a, 0x9d, 0x2e, 0xde, 0x74, 0xee, 0x80, 0xda, 0x50, 0xf6, 0x0d, 0x1b, 0xf3, 0xca, 0xce,
	0xe7, 0x62, 0xe2, 0x9b, 0xde, 0x1e, 0xe9, 0x51, 0x1f, 0xf5, 0x6b, 0x28, 0xdf, 0x0b, 0x71, 0xf0,
	0xe2, 0x0e, 0x88, 0xb7, 0xa0, 0xce, 0x9a, 0x3b, 0x4e, 0x23, 0xd9, 0xd0, 0xcb, 0xb2, 0xc4, 0xff,
	0x93, 0x56, 0x4b, 0xdd, 0xd2, 0xa3, 0x61, 0x0b, 0x90, 0xb8, 0x9a, 0x93, 0x75, 0x49, 0x12, 0xaa,
	0xb4, 0x3a, 0x51, 0xa9, 0x07, 0xf3, 0x71, 0x87, 0x8a, 0x81, 0x9f, 0xeb, 0x89, 0xf0, 0x26, 0x2c,
	0x0c, 0xe3, 0x4d, 0x96, 0xaa, 0x0f, 0x75, 0xd6, 0x93, 0xd3, 0xb0, 0x34, 0xd5, 0x29, 0xb0, 0x05,
	0x48, 0x8c, 0x38, 0x59, 0xba, 0x9b, 0x50, 0x67, 0x0d, 0x3c, 0x39, 0xb7, 0xea, 0x12, 0x20, 0x71,
	0x2d, 0xef, 0xfc, 0xdf, 0x4a, 0x30, 0x1f, 0x37, 0x86, 0x08, 0xf8, 0x12, 0xb5, 0xfd, 0x23, 0xa8,
	0x27, 0xd5, 0x0d, 0x7b, 0xfe, 0xb2, 0xdc, 0xf3, 0xf2, 0xfe, 0x4e, 0xd3, 0xf0, 0xdf, 0x94, 0xe0,
	0xcc, 0x8d, 0x80, 0x0c, 0xfc, 0x17, 0xd7, 0xf2, 0x6f, 0x27, 0x4d, 0x4b, 0xf3, 0x48, 0x76, 0x73,
	0x5d, 0x56, 0xf3, 0xb9, 0xb4, 0x5a, 0xe6, 0x97, 0x36, 0xfd, 0x55, 0x58, 0xcc, 0xac, 0xe7, 0x74,
	0xfd, 0x4f, 0xd2, 0xa6, 0xbc, 0x3e, 0x11, 0x27, 0x61, 0x6d, 0x98, 0x09, 0xfe, 0x5c, 0xfb, 0x7e,
	0x0b, 0xea, 0x42, 0xc0, 0x09, 0xb3, 0x0d, 0x92, 0x3e, 0x9c, 0x8e, 0xac, 0xa9, 0x7a, 0xff, 0x2a,
	0x2c, 0x66, 0x62, 0x4e, 0x98, 0xf2, 0x56, 0xd2, 0xc1, 0x53, 0x50, 0xac, 0x2e, 0xc3, 0x62, 0x66,
	0x31, 0xef, 0xff, 0xdf, 0x4b, 0xb0, 0x10, 0x77, 0x48, 0x06, 0xf2, 0x25, 0x3a, 0x00, 0x3e, 0x63,
	0x83, 0x0d, 0x2d, 0x2f, 0x14, 0x26, 0x2e, 0xe9, 0x04, 0xc8, 0x6d, 0xf3, 0x14, 0x47, 0x40, 0xf7,
	0x53, 0x38, 0xbb, 0x1d, 0xd3, 0x7f, 0xcd, 0x75, 0xee, 0xc6, 0x34, 0xde, 0x06, 0xb8, 0x81, 0x23,
	0x7e, 0xb1, 0x40, 0xe7, 0x73, 0x02, 0xb9, 0x1e, 0xdf, 0x50, 0x95, 0x46, 0x1a, 0x5a, 0xba, 0x82,
	0xa8, 0x0b, 0x4f, 0x7f, 0xf9, 0xf3, 0xdb, 0x19, 0x40, 0x35, 0x9d, 0x5f, 0x3d, 0xba, 0x7f, 0x95,
	0xa1, 0x96, 0x8c, 0x30, 0xc8, 0x84, 0x0a, 0x6b, 0x57, 0x74, 0x21, 0x85, 0x28, 0xba, 0x13, 0x28,
	0xff, 0x1d, 0x65, 0xe6, 0x71, 0x14, 0x1a, 0x67, 0x49, 0x9d, 0xd5, 0x0d, 0x8e, 0xbd, 0x99, 0xca,
	0x1c, 0x43, 0x39, 0xee, 0x31, 0xb4, 0x9a, 0x62, 0xe4, 0xe7, 0x7d, 0x65, 0xad, 0xd8, 0xc8, 0xe1,
	0x55, 0x0a, 0xbf, 0x86, 0x94, 0x14, 0x5e, 0xff, 0xd2, 0xb1, 0xb4, 0xe4, 0xa2, 0xb8, 0xeb, 0x58,
	0x5f, 0xa1, 0x1f, 0x4b, 0x50, 0x61, 0xad, 0x21, 0x14, 0x53, 0x34, 0xa5, 0x0b, 0xc5, 0x14, 0x0e,
	0xd3, 0xea, 0xa3, 0x5f, 0x7f, 0x6a, 0xce, 0xd4, 0x4e, 0xd1, 0x98, 0x0f, 0x15, 0x55, 0x88, 0xc9,
	0x4b, 0xd2, 0xa4, 0xd8, 0x69, 0xad, 0x0f, 0x3a, 0xdd, 0x49, 0xdc, 0xd1, 0x13, 0xa8, 0xb0, 0x8e,
	0x12, 0x52, 0x2e, 0x9a, 0xce, 0x85, 0x94, 0x8b, 0xa7, 0x6f, 0xfd, 0xe4, 0xb8, 0x39, 0x9b, 0xde,
	0x29, 0x19, 0x5b, 0xed, 0x7f, 0x62, 0xeb, 0x1e, 0x94, 0x63, 0x51, 0x0b, 0x9b, 0x92, 0x1f, 0xde,
	0x95, 0x0b, 0x45, 0xc6, 0xb4, 0x05, 0xd4, 0x3a, 0x8d, 0x33, 0x87, 0x86, 0x9b, 0xae, 0xf0, 0x2f,
	0xc9, 0xc2, 0xa9, 0xee, 0x0f, 0x65, 0x38, 0x43, 0xbf, 0x99, 0xe8, 0x41, 0x2a, 0x32, 0x45, 0x52,
	0x91, 0x30, 0x31, 0x28, 0xab, 0x85, 0x36, 0x1e, 0x69, 0x85, 0x46, 0xaa, 0xab, 0x15, 0x7d, 0x10,
	0x43, 0x0e, 0x09, 0x7c, 0xc8, 0xb5, 0xd5, 0xc8, 0xc8, 0x47, 0xc4, 0x6d, 0x16, 0x58, 0x38, 0xea,
	0x45, 0x8a, 0xda, 0x44, 0x2b, 0x0c, 0x35, 0x4f, 0xd2, 0x77, 0x43, 0x49, 0x29, 0x92, 0x66, 0x8a,
	0x53, 0xcf, 0x8f, 0x65, 0x6a, 0x5f, 0x10, 0xd3, 0x7d, 0xe5, 0x62, 0x12, 0xea, 0x99, 0x4a, 0x6a,
	0x77, 0xc7, 0xf6, 0x45, 0x6e, 0x2a, 0x23, 0x45, 0xd2, 0x49, 0x71, 0x9a, 0x05, 0x43, 0xdc, 0xff,
	0x4f, 0x8e, 0x9b, 0x15, 0x76, 0xe1, 0x60, 0xac, 0xb4, 0x47, 0xb2, 0x72, 0x8b, 0x4b, 0xa7, 0x91,
	0x51, 0x87, 0x18, 0x49, 0xc9, 0x59, 0x86, 0xa2, 0x39, 0x47, 0xe1, 0x6b, 0x88, 0x6f, 0xa5, 0xa0,
	0x98, 0x9f, 0xcb, 0x50, 0x61, 0x87, 0x2c, 0xfa, 0x24, 0x95, 0x8c, 0x2c, 0x0b, 0xf1, 0x23, 0x23,
	0x1c, 0x1a, 0x05, 0x43, 0x87, 0xda, 0xa0, 0x91, 0x90, 0x5a, 0xd5, 0x6d, 0x8a, 0x3a, 0xe4, 0x6b,
	0x97, 0xab, 0x26, 0xab, 0x8d, 0x0c, 0xb4, 0x52, 0x64, 0xe2, 0xc0, 0x2d, 0x0a, 0xac, 0xa0, 0x06,
	0x07, 0xce, 0x53, 0xf4, 0xfd, 0x50, 0x38, 0xb2, 0x38, 0x46, 0x14, 0x50, 0xf0, 0x51, 0x57, 0x2d,
	0x41, 0x3a, 0x1f, 0x2b, 0xad, 0x34, 0xda, 0x33, 0xb5, 0xb3, 0xd1, 0x1d, 0xdf, 0x19, 0xf9, 0xa9,
	0x78, 0x64, 0x81, 0x8c, 0x48, 0xb5, 0x68, 0x06, 0xd8, 0x38, 0x39, 0x6e, 0x56, 0xf9, 0xf4, 0xca,
	0xd8, 0x69, 0x8f, 0x66, 0xe7, 0x23, 0x2e, 0xa0, 0x66, 0x46, 0x26, 0x99, 0x68, 0xab, 0x79, 0xd3,
	0x50, 0x42, 0xf3, 0x34, 0xc2, 0x2c, 0x4a, 0x36, 0x76, 0xa8, 0xa1, 0x9d, 0xce, 0x83, 0x8d, 0x71,
	0xff, 0x05, 0xde, 0xf2, 0xfb, 0xfd, 0x0a, 0xfd, 0x90, 0xbe, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0x47, 0x8c, 0x3b, 0x3b, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AtlasCliTestClient is the client API for AtlasCliTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AtlasCliTestClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type atlasCliTestClient struct {
	cc *grpc.ClientConn
}

func NewAtlasCliTestClient(cc *grpc.ClientConn) AtlasCliTestClient {
	return &atlasCliTestClient{cc}
}

func (c *atlasCliTestClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.AtlasCliTest/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtlasCliTestServer is the server API for AtlasCliTest service.
type AtlasCliTestServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterAtlasCliTestServer(s *grpc.Server, srv AtlasCliTestServer) {
	s.RegisterService(&_AtlasCliTest_serviceDesc, srv)
}

func _AtlasCliTest_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasCliTestServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AtlasCliTest/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasCliTestServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AtlasCliTest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AtlasCliTest",
	HandlerType: (*AtlasCliTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AtlasCliTest_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/atlas-cli-test/pkg/pb/service.proto",
}

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	// Use this method to create a Account information.
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// Use this method to read a Account information by identifier.
	Read(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadAccountResponse, error)
	// Use this method to update a Account information.
	Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	// Use this method to delete a particular Account.
	Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	// Use this method to retrieve all the Accounts.
	List(ctx context.Context, in *ListAccountRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/service.Accounts/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Read(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadAccountResponse, error) {
	out := new(ReadAccountResponse)
	err := c.cc.Invoke(ctx, "/service.Accounts/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := c.cc.Invoke(ctx, "/service.Accounts/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/service.Accounts/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) List(ctx context.Context, in *ListAccountRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/service.Accounts/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	// Use this method to create a Account information.
	Create(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// Use this method to read a Account information by identifier.
	Read(context.Context, *ReadAccountRequest) (*ReadAccountResponse, error)
	// Use this method to update a Account information.
	Update(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	// Use this method to delete a particular Account.
	Delete(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	// Use this method to retrieve all the Accounts.
	List(context.Context, *ListAccountRequest) (*ListAccountsResponse, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Accounts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Accounts/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Read(ctx, req.(*ReadAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Accounts/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Update(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Accounts/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Delete(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Accounts/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).List(ctx, req.(*ListAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Accounts_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Accounts_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Accounts_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Accounts_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Accounts_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/atlas-cli-test/pkg/pb/service.proto",
}

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	// Use this method to create a User information.
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// Use this method to read a User information by identifier.
	Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error)
	// Use this method to update a User information.
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// Use this method to delete a particular User.
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// Use this method to retrieve all the Users.
	List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error) {
	out := new(ReadUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/service.Users/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	// Use this method to create a User information.
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// Use this method to read a User information by identifier.
	Read(context.Context, *ReadUserRequest) (*ReadUserResponse, error)
	// Use this method to update a User information.
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// Use this method to delete a particular User.
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// Use this method to retrieve all the Users.
	List(context.Context, *ListUserRequest) (*ListUsersResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Read(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).List(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Users_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Users_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/atlas-cli-test/pkg/pb/service.proto",
}

// GroupsClient is the client API for Groups service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupsClient interface {
	// Use this method to create a Group information.
	Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	// Use this method to read a Group information by identifier.
	Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error)
	// Use this method to update a Group information.
	Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	// Use this method to delete a particular Group.
	Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	// Use this method to retrieve all the Groups.
	List(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Create(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, "/service.Groups/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Read(ctx context.Context, in *ReadGroupRequest, opts ...grpc.CallOption) (*ReadGroupResponse, error) {
	out := new(ReadGroupResponse)
	err := c.cc.Invoke(ctx, "/service.Groups/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Update(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, "/service.Groups/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Delete(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	out := new(DeleteGroupResponse)
	err := c.cc.Invoke(ctx, "/service.Groups/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) List(ctx context.Context, in *ListGroupRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/service.Groups/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupsServer is the server API for Groups service.
type GroupsServer interface {
	// Use this method to create a Group information.
	Create(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	// Use this method to read a Group information by identifier.
	Read(context.Context, *ReadGroupRequest) (*ReadGroupResponse, error)
	// Use this method to update a Group information.
	Update(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	// Use this method to delete a particular Group.
	Delete(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	// Use this method to retrieve all the Groups.
	List(context.Context, *ListGroupRequest) (*ListGroupsResponse, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Groups/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Create(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Groups/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Read(ctx, req.(*ReadGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Groups/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Update(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Groups/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Delete(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Groups/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).List(ctx, req.(*ListGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Groups_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Groups_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Groups_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Groups_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Groups_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/seizadi/atlas-cli-test/pkg/pb/service.proto",
}
